#!/usr/bin/env bash
# Install LimitLens: the collector library, the CLI, and the GNOME extension.
set -euo pipefail

UUID="limitlens@devded.pm.me"
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/limitlens"
EXT_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/gnome-shell/extensions/$UUID"
BIN_DIR="$HOME/.local/bin"

PYTHON_BIN="$(command -v python3 || command -v python || echo "/usr/bin/python3")"

echo "Installing LimitLens (using $PYTHON_BIN)"

# 1. Collector library.  The extension spawns python with this
#    as the working directory, so the package must live at lib/limitlens.
mkdir -p "$DATA_DIR/lib"
rm -rf "$DATA_DIR/lib/limitlens"
cp -r "$SRC/lib/limitlens" "$DATA_DIR/lib/limitlens"
find "$DATA_DIR/lib" -name '__pycache__' -type d -prune -exec rm -rf {} +
echo "  collector  -> $DATA_DIR/lib/limitlens"

# 2. CLI shim.
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/limitlens" <<EOF
#!/usr/bin/env bash
# limitlens CLI — generated by install.sh
exec "$PYTHON_BIN" -c 'import sys; sys.path.insert(0, "$DATA_DIR/lib"); from limitlens.__main__ import main; sys.exit(main())' "\$@"
EOF
chmod +x "$BIN_DIR/limitlens"
echo "  cli        -> $BIN_DIR/limitlens"

# 3. Status line hook (standalone and import-light — it runs inside Claude
#    Code's render path, so it must stay cheap).
install -m 755 "$SRC/hooks/limitlens-statusline" "$BIN_DIR/limitlens-statusline"
echo "  hook       -> $BIN_DIR/limitlens-statusline"

# 4. GNOME Shell extension.
mkdir -p "$EXT_DIR"
cp "$SRC/extension/extension.js" "$SRC/extension/metadata.json" \
   "$SRC/extension/stylesheet.css" "$EXT_DIR/"
echo "  extension  -> $EXT_DIR"

# 5. Prime the cache so the panel has something to show immediately.
echo
echo "Reading the current limits..."
"$PYTHON_BIN" -c "import sys; sys.path.insert(0, '$DATA_DIR/lib'); from limitlens import collect; collect.run(force=True)" || true

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo; echo "Note: $BIN_DIR is not on your PATH." ;;
esac

cat <<EOF

Done.

  limitlens            print the limits
  limitlens --watch    live dashboard
  limitlens --install-hook   let Claude Code push its limits (recommended)

To enable the top bar extension, log out and back in (GNOME on Wayland cannot
load new extension code without a session restart), then:

  gnome-extensions enable $UUID
EOF

